USE DB_FINTECH
GO

CREATE TABLE TB_ENDERECOS (
	ID INT PRIMARY KEY IDENTITY(1,1),
	CEP VARCHAR(8) NOT NULL,
	LOGRADOURO VARCHAR(80) NOT NULL,
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(20) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	UF VARCHAR(2) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL,
	CHECK(LEN(CEP) = 8)
)
GO

CREATE TABLE TB_PESSOAS (
	ID INT PRIMARY KEY IDENTITY(1,1),
	CPF VARCHAR(11) UNIQUE NOT NULL,
	NOME VARCHAR(80) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	ID_ENDERECO INT NOT NULL,
	FOREIGN KEY(ID_ENDERECO) REFERENCES TB_ENDERECOS(ID),
	CHECK(LEN(CPF) = 11)
)
GO

CREATE TABLE TB_AGENCIAS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NUMERO VARCHAR(4) UNIQUE NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	RAZAO_SOCIAL VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	CHECK (LEN(NUMERO) = 4)
)
GO

CREATE TABLE TB_ADMINS (
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_PESSOA INT NOT NULL,
	USERNAME VARCHAR(11) UNIQUE NOT NULL,
	SENHA VARCHAR(16) NOT NULL
	FOREIGN KEY(ID_PESSOA) REFERENCES TB_PESSOAS(ID),
	CHECK (LEN(USERNAME) BETWEEN 5 AND 11),
	CHECK (LEN(SENHA) BETWEEN 8 AND 16)
)
GO

CREATE TABLE TB_CLIENTES (
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_PESSOA INT NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	FOREIGN KEY(ID_PESSOA) REFERENCES TB_PESSOAS(ID),
	CHECK (LEN(SENHA) BETWEEN 8 AND 16)
)
GO

CREATE TABLE TB_CONTAS (
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_AGENCIA INT NOT NULL,
	ID_CLIENTE INT UNIQUE NOT NULL,
	ID_ADMIN INT NOT NULL,
	NUMERO VARCHAR(10) UNIQUE NOT NULL,
	TIPO SMALLINT NOT NULL,
	SALDO DECIMAL DEFAULT 0,
	DATA_ABERTURA DATETIME NOT NULL,
	DATA_ENCERRAMENTO DATETIME,
	DATA_ULTIMO_ACESSO DATETIME,
	SITUACAO SMALLINT NOT NULL,
	CHECK(TIPO = 1 OR TIPO = 2), /* 1- Simples 2- Premium*/
	CHECK(SITUACAO = 1 OR SITUACAO = 2), /* 1- ABERTA, 2- FECHADA */
	FOREIGN KEY(ID_AGENCIA) REFERENCES TB_AGENCIAS(ID),
	FOREIGN KEY(ID_CLIENTE) REFERENCES TB_CLIENTES(ID),
	FOREIGN KEY(ID_ADMIN) REFERENCES TB_ADMINS(ID)
)
GO

CREATE TABLE TB_CHAVES_PIX (
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_CONTA INT NOT NULL,
	TIPO SMALLINT NOT NULL,
	CHAVE VARCHAR(50) NOT NULL,
	CHECK(TIPO BETWEEN 1 AND 4),  /*1- cpf, 2- email, 3- telefone, 4- aleatória*/
	FOREIGN KEY(ID_CONTA) REFERENCES TB_CONTAS(ID)
)
GO

CREATE TABLE TB_TRANSACOES(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_CONTA_ORIGEM INT NOT NULL,
	TIPO_TRANSACAO SMALLINT NOT NULL,
	AGENCIA_DESTINO VARCHAR(4),
	NUMERO_CONTA_DESTINO VARCHAR(20),
	CHAVE_DESTINO VARCHAR(50),
	TIPO_PIX SMALLINT,
	CODIGO_BARRAS VARCHAR(50),
	VALOR DECIMAL NOT NULL,
	DATA_TRANSACAO DATETIME NOT NULL,
	DATA_VENCIMENTO DATE,
	NUMERO_PROTOCOLO VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(100),
	TAXA DECIMAL DEFAULT 13,
	CHECK (VALOR > 0),
	CHECK (TIPO_TRANSACAO BETWEEN 1 AND 5), /*1- DEPOSITO, 2- SAQUE* 3- PIX 4-BOLETO 5-DEBITO*/
	CHECK(TIPO_PIX BETWEEN 1 AND 4),  /*1- cpf, 2- email, 3- telefone, 4- aleatória*/
	FOREIGN KEY(ID_CONTA_ORIGEM) REFERENCES TB_CONTAS(ID)
)
GO

CREATE TABLE TB_EXTRATO (
	ID INT PRIMARY KEY IDENTITY(1,1),
    ID_CONTA INT NOT NULL,
	ID_TRANSACAO INT NOT NULL,
    SALDO_ANTERIOR DECIMAL NOT NULL,
    SALDO_POSTERIOR DECIMAL NOT NULL,
    CONSTRAINT chk_valor_positivo CHECK (VALOR > 0),
	CHECK(TIPO_MOVIMENTACAO BETWEEN 1 AND 5),  /*? 1- PIX, 2- transferencia, 3- depósito, 4- saque 5-pagamento*/
	FOREIGN KEY(ID_CONTA) REFERENCES TB_CONTAS(ID)
)
GO

CREATE TABLE TB_CARTOES (
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_CONTA INT NOT NULL,
	DATA_CRIACAO DATETIME NOT NULL,
	NUMERO_CARTAO VARCHAR(16) NOT NULL UNIQUE,
	CVC VARCHAR(3) NOT NULL,
	VALIDADE DATE NOT NULL,
	TAXA DECIMAL NOT NULL,
	SENHA VARCHAR(4) NOT NULL,
	APROXIMACAO SMALLINT NOT NULL,
	SITUACAO SMALLINT NOT NULL,
	FOREIGN KEY(ID_CONTA) REFERENCES TB_CONTAS(ID),
	CHECK(LEN(SENHA) = 4),
	CHECK(APROXIMACAO BETWEEN 1 AND 2), /* 1- ATIVADO, 2- DESATIVADO */
	CHECK(SITUACAO BETWEEN 1 AND 3) /* 1- DESBLOQUEADO, 2- BLOQUEADO, 3- CANCELADO */
)
GO